version: '3'
services:
    db:
        image: postgres:12
        container_name: postgres-db
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB

    web:
        image: node:16
        container_name: node-api
        build: ./
        ports:
            - 3000:3000
        env_file: ./.env
        environment:
            - POSTGRES_HOST=$POSTGRES_HOST
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        depends_on:
            - db
        command: npm start

volumes:
    pgdata:
